### PR TITLE
README Rework

### PR DESCRIPTION
**Pull request by ElectronicsArchiver**
[Badge Suggestions]: https://img.shields.io/badge/Ｒｅｐｏｓｉｔｏｒｙ_Ｓｕｇｇｅｓｔｉｏｎｓ-609926?style=for-the-badge&logoColor=white&logo=GitHub
[Badge Changes]: https://img.shields.io/badge/Ｃｈａｎｇｅｓ-D81939?style=for-the-badge&logoColor=white&logo=GitLFS
[Badge Ask]: https://img.shields.io/badge/Ｐｌｅａｓｅ_Ａｓｋ_Ｍｅ-73398D?style=for-the-badge&logoColor=white&logo=AskUbuntu

[Widgets]: https://github.com/MarkedDown/Disable/blob/main/Features/Widgets.md
[Tabs]: https://github.com/MarkedDown/Disable/blob/main/Features/Tabs.md

<br>
<br>

<div align = center>

[<kbd> <br> Please Check The **Preview** <br> </kbd>][Preview]

</div>
  
<br>
<br>

## ![Badge Suggestions]

  <br>

- **Add Tags**

  <br>

- **Choose A License**

  Not necessarily for the firmware, but for
  the repository itself / documentation.

  Especially to avoid the disclaimer
  section being plastered in READMEs.

  In case you choose one of the following
  licenses I'll consider this PR to under
  said license.

  **⤷** *https://choosealicense.com/licenses/*

  <br>

- ***[Disable Unused Widgets][Widgets]***:

  - `Packages`

  <br>

- ***[Disable Unused Tabs][Tabs]***:

  - `Actions`

<br>
<br>

## ![Badge Changes]

- Separated sections into topics

- General formatting / spacing

- Converted raw links into link references

- Added quicklinks

- Temporarily moved the disclaimer

<br>
<br>

## ![Badge Ask]

- ***If you have any questions.***

- ***In case you do not agree with some of the changes made in this PR***, <br>
  *please first let me know about them, before disregarding it entirely so*<br>
  *we can possibly find a middle ground and have it not go to waste.*

<br>
<br>

[Preview]: https://github.com/ElectronicsArchiver/firmware

### CODE REVIEW

**Comment by marcus-j-davies** [comment]
@ElectronicsArchiver,

Your issue links need updating.
If you look at my PR, you will see the new links.

@jascoproducts have updated the templates ever so slightly, my PR addresses it for the read me, it looks as if your PR contains the wrong links, copy them from my PR and you should be current. 👍

**Comment by ElectronicsArchiver** [comment]
@marcus-j-davies

Sure, will do. 

*( Didn't wanna 'take your work'~ )*

**Comment by marcus-j-davies** [comment]
Nah, my PR is just to correct the links. If you use the ones in my PR. Your golden.

Your is a rework of the read me, mine isn't 😉

**Comment by jascoproducts** [comment]
@ElectronicsArchiver Thanks for all the great work! We'd like to exchange some ideas with you.

SECURITY.md and your formatting style looks great, but we have some specific requirements before we'd consider merging.

1. Please leave the disclaimer literature as it was. Our disclaimers throughout the repository are conspicuous by design. We have already reviewed this firmware project with our legal department and have decided to implement those as an alternative to choosing to defer to another software license.

2. Please remove the Topics folder and hotlinks for Identifying Your Product and Updating Firmware. We are actively considering ways to update the readme to make it more accessible, but we have decided that the literature, rather than be broken off into topics, should be contained within and accessible from the main README.md. We want to avoid requiring users to click and acknowledge separate links.

Let us know your thoughts and feel free to make changes for further review. Looking forward to working with you.

**Comment by jascoproducts** [comment]
Thanks for the great work; looks fantastic. Merged your commits.

Thanks also for the info about licenses. Are there any specific problems you or other potential collaborators could foresee/currently are running into if we continue as-is without declaring a license? We're wanting to gain some more information before we bring others forward internally to discuss issuing one.

**Comment by jascoproducts** [comment]
@ElectronicsArchiver Thanks for the super detailed info on the license. We are in the process of choosing one.

Would you be willing to make another button and section for Finding Your Firmware? We want to show users how to search for firmware using this method:

# 1. image
# 2. image

**Comment by ElectronicsArchiver** [comment]
Sure, do you have an example string for the
search / found firmware you want to use?

**Comment by jascoproducts** [comment]
Let's do:

- "you can search for a Z-Wave number" = ZW4008
- "or a specific model number" = 46201

Does not have to be that exact wording in quotes but that's what we'd like to convey.

**Pull request merged**
